# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 6",
   "iPhone 6 Plus",
   "iPhone 5",
   "iPad Pro (12.9 inch)",
   "iPad Pro (9.7 inch)"
])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme "Motivation Hunt"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones
reinstall_app true
clean true
# Choose which project/workspace to use
project "./Motivation Hunt.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])
# reinstall_app true

# For more information about all available options run
# snapshot --help
